### ISSUE TITLE
Migrate to AWS

### ISSUE THREAD

**Issue by GirlBossRush** [ConzorKingKong/react-hacker-news-api#6]
The goal of this change is to:
- Make this this project available at hn.connorpeshek.com
- Learn about Amazon Web Services (S3, Route 53, CloudFront)
- Learn about static site deployment.

This will move the DNS server for connorpeshek.me to Route 53, Amazon's routing tool.
CloudFront is Amazon's caching and redirection layer. This lets hn.connorpeshek.me/comment/123 still redirect to your index.html for a client-side router to use, rather than a 404 error.

Read this doc in full along with its individual steps before continuing. This will give you a general idea of what the journey looks like. I suspect these docs were a second-draft by an intern so they're a little rough. 😉 

http://docs.aws.amazon.com/gettingstarted/latest/swh/website-hosting-intro.html

## DNS guidelines
- [x] Migrate connorpeshek.me to AWS Route 53
- [x] Carefully add your existing DNS records to Route 53. This can take a few minutes to propagate.
- [x] Are the MX records configured right? Test incoming email to connor@connorpeshek.me
- [x] Is your homepage configured right? Test connorpeshek.me and www.connorpeshek.me

## Build guidelines
- [x] Configure Webpack to generate its build in a directory.
- [x] Use [Stout](http://stout.is/)

**Comment by PeshekDotDev** [comment]
Done
